### ISSUE TITLE
Only enforce coverage threshold across all files 

### ISSUE THREAD

**Issue by kbrooks** [GetJobber/jest-a-coverage-slip-detector#23]
Hey, I found this package while trying to get code coverage working with my sharded jest tests after seeing it mentioned here https://github.com/facebook/jest/issues/12751. I want to use this project to get the same coverage enforcement we have on our project with jest's built-in coverage reporter, but with the speed of jest shards.

However, it seems like the project forces you to fail the check if any file in the repository is beneath the configured threshold. 

Is it possible to add support for the following:
* Running a coverage check that fails only if coverage is low across all files
* Creating a coverage summary from the merged coverage

**Comment by jcw-** [comment]
Sorry for the delayed response - I completely missed this notification!

I think what you likely want to do is to "accept" the current coverage results of your codebase, which means that each file will have its own "custom threshold", and it will only be allowed to go upwards from there (until it is over the over-all threshold). Brand new files will be subject to the over-all threshold.

Check out step 2 of the "First Run" section in the readme:

> Snapshot current coverage errors as legacy exceptions: npm run test:setCoverageExceptionsBaseline
