### ISSUE TITLE
Can't run test:validateCoverage locally if mergeCoveragePath is set

### ISSUE THREAD

**Issue by schinery** [GetJobber/jest-a-coverage-slip-detector#31]
Moving over to this from another Jest coverage module and so far, everything is going great except for one thing... 

I've setup the config to use `mergeCoveragePath: "some_folder"` as the tests have been setup to run in parallel on the CI, however this has resulted in not being able to run tasks such as `test:validateCoverage` locally as I then get this error:

```sh
❯ npm run test:validateCoverage

> my-jest-project@0.0.1 test:validateCoverage
> npx jest-a-coverage-slip-detector

node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'some_folder'
```

Wondering if there are any ways around this barring creating `some_folder` locally and copying the coverage.json out of the original coverage folder?

**Comment by jcw-** [comment]
Thanks for reporting this issue! I've added extra validation to check if the directory exists with which gives a better error message in case you try to run the validation step when there isn't any output to process, what do you think of this approach?

https://github.com/GetJobber/jest-a-coverage-slip-detector/pull/32

**Comment by schinery** [comment]
The extra validation is good/better error message is definitely a good thing, however it doesn't help with our use case, which is that we can't run `npm run test:validateCoverage` locally if the tests are setup to run in parallel on the CI.

Having a look at the [parallelism docs](https://github.com/GetJobber/jest-a-coverage-slip-detector#concurrency-and-parallelism) again though, is it the case that the `mergeCoveragePath` option could/should be ignored if the `--merge` argument isn't given?

Otherwise, there is no way to run the `jest-a-coverage-slip-detector` commands locally if using this setup.

**Comment by schinery** [comment]
Or maybe need `coveragePath` and `mergeCoveragePath` config options [here](https://github.com/GetJobber/jest-a-coverage-slip-detector/blob/main/src/config.js#L21)?

**Comment by jcw-** [comment]
The validate coverage command checks your latest persisted results against the targets and exceptions. You have to run the jest tests with coverage enabled to generate the results ahead of that though, e.g. `npm run test:generateCoverage && npm run test:validateCoverage` - does it work correctly when you run it like that?

**Comment by schinery** [comment]
> does it work correctly when you run it like that?

No, because jest is configured to store the coverage output in a `coverage` folder, so when `npm run test:generateCoverage` runs it outputs the coverage to that directory, but then when `npm run test:validateCoverage` runs it is looking for the `mergeCoveragePath` directory.

This is correct for the CI because we are doing the following:

```
# Run in parallel, generate multiple files
COVERAGE_REPORT_SHARD=final-coverage-files/coverage-final${CIRCLE_NODE_INDEX}.json
npm run test:ci $TESTFILES && mv coverage/coverage-final.json $COVERAGE_REPORT_SHARD

# In another job to validate all the test coverage
npm run test:validateCoverage -- --merge
```

But not locally, because `final-coverage-files` doesn't exist.

**Comment by schinery** [comment]
Just digging through the code, is it the case that currently https://github.com/GetJobber/jest-a-coverage-slip-detector/blob/main/src/mergeCoverage.js#L50 is running all the time but should only run if the `--merge` flag is present?

**Comment by jcw-** [comment]
Oh and yes, merge actually happens all the time, by default (there is actually a config that defaults to true for that called `alwaysMerge`), which I had to add to compensate for incorrect coverage output from jest: https://github.com/GetJobber/jest-a-coverage-slip-detector/pull/19

**Comment by jcw-** [comment]
So the root problem here is that in CI, the CI script has special knowledge of how to shift the jest coverage output to the desired target location, but when running locally, nothing has that knowledge.

What I'm thinking is that when running locally and the merge flag is absent, and the target folder doesn't exist, it should fallback to the coverage folder configured in jest (which should be detectable). Let me try that...

**Comment by jcw-** [comment]
So it's actually not as easily detectable as I was imagining - and really, that's getting a bit complicated - on second thought, let's just turn the workaround into the solve - instead of allowing a configurable output directory that might be different than jest, let's just dictate that it needs to be the same. Easy peasy.

Check [the PR](https://github.com/GetJobber/jest-a-coverage-slip-detector/pull/32) for the updates to the documentation and let me know what you think!

**Comment by schinery** [comment]
Doesn't look like making those changes will work.

I've updated `"mergeCoveragePath": "coverage"` and the CI task is now:

```sh
cp -R coverage/coverage-final.json coverage/coverage-${CIRCLE_NODE_INDEX}.json
```

But now when the validate task runs a lot of the coverage is missing. I don't know if that is down to how CircleCI is attaching the workspace in the coverage job or not though. 

We are using this to store the coverage on the CI (using CircleCI)

```yml
      - persist_to_workspace:
          root: .
          paths:
            - coverage
```

And then this in the coverage job

```yml
      - attach_workspace:
          at: .
```

Before this change it would have been persisting the merge directory "some_folder" and there would be no filename clashes between the JSON files. I wonder if now it is storing the entire coverage directory, with the same html files etc it is causing an issue.

**Comment by schinery** [comment]
I do have a hack around this issue...

```json
    "test:ci:validateCoverage": "npx jest-a-coverage-slip-detector",
    "test:validateCoverage": "mkdir -p ci-coverage && cp coverage/coverage-final.json ci-coverage/ && jest-a-coverage-slip-detector"
```

**Comment by jcw-** [comment]
> But now when the validate task runs a lot of the coverage is missing.

It looks like you're outputting your sharded coverage as `coverage-1.json`, `coverage-2.json` - if so, you'll need to update the config `input: { mergePrefix: "coverage-final" }` to be `"coverage"`, or else it will only pick-up the final shard's output

should be working locally though, right?

**Comment by schinery** [comment]
Did the above changes (used `coverage-final-${CIRCLE_NODE_INDEX}.json`) and was able to ditch the workaround too.

Thanks for the help.
